@baseUrl = http://localhost:3000
@todoId = 1

### API Test for Todos
### Get All Todos
GET {{baseUrl}}/api/todos
Content-Type: application/json

###

### Add a New Todo
POST {{baseUrl}}/api/todos
Content-Type: application/json

{
  "title": "New Todo"
}

###

### Get a Todo by ID
GET {{baseUrl}}/api/todos/{{todoId}}
Content-Type: application/json

###

### Update a Todo
PUT {{baseUrl}}/api/todos/{{todoId}}
Content-Type: application/json

{
  "title": "Updated Todo Title"
}

###

### Delete a Todo
DELETE {{baseUrl}}/api/todos/{{todoId}}
Content-Type: application/json