@baseUrl = http://localhost:3000
@todoId = 1

### API Test for Todos
### Get All Todos
GET {{baseUrl}}/api/todos
Content-Type: application/json

###

### Add a New Todo
POST {{baseUrl}}/api/todos
Content-Type: application/json

{
  "title": "New Todo"
}

###

### Get a Todo by ID
GET {{baseUrl}}/api/todos/{{todoId}}
Content-Type: application/json

###

### Update a Todo
PUT {{baseUrl}}/api/todos/{{todoId}}
Content-Type: application/json

{
  "title": "Updated Todo Title"
}

###

### Delete a Todo
DELETE {{baseUrl}}/api/todos/{{todoId}}
Content-Type: application/json

###

### Sign-Up
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

###

### Sign-In
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}
