import type { Metadata } from 'next'

// These styles apply to every route in the application
import './globals.css'
import { ReactNode } from 'react';
import { Toaster } from "sonner";

import NavMenu from "@/(presentation)/components/NavMenu";
import { Providers } from './providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    {/* Navigation Menu */}
                    <header className="bg-gray-100 shadow-md">
                        <div className="container mx-auto p-4">
                            <NavMenu />
                        </div>
                    </header>
                    {/* Main Content */}
                    <Toaster position="bottom-center" richColors />
                    <main className="container mx-auto p-4">{children}</main>
                </Providers>
            </body>
        </html>
    )
}