import type { Metadata } from 'next'

// These styles apply to every route in the application
import './globals.css'
import NavMenu from "@/presentation/components/NavMenu";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactNode } from "react";

const queryClient = new QueryClient();

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <QueryClientProvider client={queryClient}>
            <html lang="en">
                <body>
                    {/* Navigation Menu */}
                    <header className="bg-gray-100 shadow-md">
                        <div className="container mx-auto p-4">
                            <NavMenu />
                        </div>
                    </header>
                    {/* Main Content */}
                    <main className="container mx-auto p-4">{children}</main>
                </body>
            </html>
        </QueryClientProvider>
    )
}